@Api_HostAddress = http://localhost:5260

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Api_HostAddress}}/api/ingredients

###
POST {{Api_HostAddress}}/api/ingredients/add
Content-Type: application/json

{
  "name": "Pasta",
  "unitOfMeasurement": "Grams"
}